import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { ThemeProvider } from "@/components/theme/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <ThemeProvider attribute="class" defaultTheme="light">
          {/* toaster */}
          <header className="border-b sticky top-0 bg-white z-50">
            <Header />
          </header>
          <div className="bg-gray-200 flex-1 w-full">
            <main>{children}</main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
